### ISSUE TITLE
reference from GitLab to GitHub 

### ISSUE THREAD

**Issue by jdsika** [ligolang/contract-catalogue#25]
Dear team,
You have archived your [GitLab](https://gitlab.com/ligolang/contract-catalogue/) repository without a link to this GitHub organization. 
We have been wrongly pointed to the GitLab without knowledge about this more recent one and wondered a week about the different transfer signature.
It would be great if you could place a big disclaimer with a redirect to the GitLab (or clone to that location with read only) in order to avoid this happening to other community members.
Thank you for this great collection!

Best regards
Carlo

**Comment by melwyn95** [comment]
Sorry for the inconvinience Carlo, we did link the github repo on the archived gitlab repo here
<img width="1095" alt="image" src="https://github.com/ligolang/contract-catalogue/assets/14284762/2c4841bd-6175-46f2-98fd-05343dd99c32">

I'll see If I can update the README, last time I checked I didn't have the permissions to push to the gitlab repo

**Comment by jdsika** [comment]
Ah, I asked in the slack for it and it apparently went in the description. I just checked the repo readme.
